version: '2'
services:
    db:
      image: mysql
      environment:
                - MYSQL_DATABASE=openbibo
                - MYSQL_USER=openbibo
                - MYSQL_PASSWORD=openbibo
                - MYSQL_ROOT_PASSWORD=root
      volumes:
            - ./db:/var/lib/mysql
      ports:
            - "3306:3306"
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: openbibo
            MYSQL_PASSWORD: openbibo
            MYSQL_ROOT_PASSWORD: root
     ports:
            - "8080:80"
     links:
            - "db:db"
    php:
     build:
      context: ./dockerfiles
      dockerfile: ./php
     volumes:
            - ./data:/var/www/html
     ports:
            - "80:80"
     links:
            - "db:db"
volumes:
    db:
        driver: "local"
